# -*- coding: utf-8 -*-
"""cancionesfavoritas(trabajo1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGp2rLITSzOjkNwOoqh4HSOCU4i8ElQm
"""

import random, time
cancionesFavoritas = ["Bohemian Rhapsody", "Don", "Highway to hell", "Take on me", "Africa", "Can't feel my face", "Naturaleza", "El perdedor", "Shut up", "Perfect strangers", "Closer"]

print("Canciones favoritas de Juliette:")
while True:
    print(random.choice(cancionesFavoritas))
    time.sleep(1)