# -*- coding: utf-8 -*-
"""diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGp2rLITSzOjkNwOoqh4HSOCU4i8ElQm
"""

meme_dict = {
    "CRINGE": "Algo excepcionalmente raro o embarazoso",
    "LOL": "Una respuesta común a algo gracioso",
    "FOMO": "Fear of missing something/ Miedo de perderse algo interesante",
    "MAL": "Literal o super sí",
    "DEA": "Es broma"
            }

word = input("Escribe una palabra que no entiendas (¡con mayúsculas!): ")
if word in meme_dict.keys():
    print(meme_dict[word])
else:
    print("Lo sentimos! Aún no tenemos esa palabra, pronto la agregaremos")